<a href="https://colab.research.google.com/github/EmmaGB/Notebooks-Curso-Big-Data/blob/main/Ejercicios_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Crear un array con valores dentro del rango 10 a 49

In [ ]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Invertir el array

In [ ]:
a=a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

3. Crear una array o matriz 1D con valores de 0 a 8. Cambiar la forma de la matriz a 3x3

In [ ]:
a=np.arange(0,9)
a
a=a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Crear una matriz identidad de 6x6

In [ ]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

5. Crear una matriz con valores al azar con forma 3x3x3 

In [ ]:
a=np.random.rand(3,3,3)
a

array([[[0.25183706, 0.57485362, 0.73962977],
        [0.69151104, 0.05226546, 0.50126541],
        [0.28378894, 0.46744688, 0.55903235]],

       [[0.38855796, 0.17022061, 0.76720981],
        [0.53769168, 0.25451883, 0.42274588],
        [0.95246763, 0.89406548, 0.39640257]],

       [[0.61983501, 0.03403208, 0.90321926],
        [0.16328638, 0.07268598, 0.77672246],
        [0.25779823, 0.87328009, 0.92722826]]])

6. Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [ ]:
indicemin=np.argmin(a)
indicemin


19

In [ ]:
indicimax=np.argmax(a)
indicimax

15

7. Crear dos arrays al azar A y B, verificar si son iguales

In [ ]:
A=np.random.rand(2,2)
B=np.random.rand(2,2)
A==B



array([[False, False],
       [False, False]])

8. Encontrar los indices que no son ceros del array [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [ ]:
a= [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]
a!= 0

True

9. Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [ ]:
matriz4=np.zeros((10,10))
matriz4[::,::9]=1
matriz4

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

10. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [ ]:
matriz=np.zeros((5,5))
matriz
matriz +=np.arange(0,5)
matriz

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])