<a href="https://colab.research.google.com/github/EmmaGB/Notebooks-Curso-Big-Data/blob/main/Ejercicios_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

1. Crear un array con valores dentro del rango 10 a 49

In [18]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Invertir el array

In [ ]:
a=np.array([10,49])
print(a)

3. Crear una array o matriz 1D con valores de 0 a 8. Cambiar la forma de la matriz a 3x3

In [10]:
a=np.array([0,1,2,3,4,5,6,7,8])
print(a)

[0 1 2 3 4 5 6 7 8]


4. Crear una matriz identidad de 6x6

In [13]:
a=np.empty((6,6))
print(a)

[[4.64510579e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]]


5. Crear una matriz con valores al azar con forma 3x3x3 

In [15]:
a=np.random.random((3,3,3))
print(a)

[[[9.88016100e-01 2.91071384e-01 6.54414544e-01]
  [8.90874631e-01 8.43118289e-01 4.02478022e-01]
  [7.89492238e-01 9.84435785e-01 6.15123612e-01]]

 [[7.33445775e-04 2.96405447e-01 2.50961375e-01]
  [6.40328112e-01 6.01689543e-01 1.48322586e-01]
  [5.38369748e-01 6.18848611e-01 8.60992030e-01]]

 [[6.28298130e-01 3.30327044e-01 5.66363071e-01]
  [7.19751158e-01 7.37192263e-02 2.15084025e-01]
  [6.31158108e-01 9.46158876e-01 1.67164433e-01]]]


6. Encontrar los indices de los valores minimos y maximos de la anterior matriz

7. Crear dos arrays al azar A y B, verificar si son iguales

8. Encontrar los indices que no son ceros del array [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

9. Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

10. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4